version: '3.9'
# --- Django: Базовый сервис ---
x-app-base: &app-base
  image: django-template:latest
  build: ./app
  hostname: web
  ports:
    - "8000:8000"
  env_file:
    - .env
  volumes:
    - ./app/static:/home/app/static/
    - ./app/media:/home/app/media/
    - ./app/log:/home/app/log/
  depends_on:
    postgres:
      condition: service_healthy
    redis:
      condition: service_healthy
  restart: always

services:
  # --- Django: Для локального тестирования ---
  django-dev:
    <<: *app-base
    command: >
      sh -c "
      uv run python manage.py migrate --noinput &&
      uv run python manage.py runserver 0.0.0.0:8000
      "
    profiles: [ "dev" ]
    restart: no

  # --- Django: Для рабочей среды ---
  django-prod:
    <<: *app-base
    command: >
      sh -c "
      uv run python manage.py migrate --noinput &&
      uv run gunicorn project.asgi:application -c project/gunicorn.conf.py
      "
    profiles: [ "prod" ]

  celery:
    <<: *app-base
    command: celery -A mfssogr worker --loglevel=INFO
    hostname: celery
    volumes:
      - ./app/log:/home/app/log

  celery-beat:
    <<: *app-base
    command: celery -A mfssogr beat -l info
    hostname: celerybeat

  # --- Redis: Кэш и очередь задач celery ---
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5

  # --- Postgres: СУБД ---
  postgres:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 60s
      retries: 3
      start_period: 10s

volumes:
  postgres_data:
  redis_data:
